### ISSUE TITLE
Change the starter kit from using a gridmap to something else

### ISSUE THREAD

**Issue by Coderchris842** [KenneyNL/Starter-Kit-City-Builder#11]
Gridmaps in godot are not very good, and it would be better if you changed the starter kit to something else so that it would be easier to give different building different effects on gameplay.

**Comment by Coderchris842** [comment]
Changing the starter kit to use something else would make it a lot easier to expand on the kit, which is the whole point of the kit.

**Comment by KenneyNL** [comment]
The gridmaps in this example work perfectly fine, as far as giving buildings effects on gameplay; that is unrelated to the rendering of the city (which the GridMap node is used for)

**Comment by Coderchris842** [comment]
Maybe you can add a building that produces money to the starter kit to provide an example of how to give building gameplay effects?
