### ISSUE TITLE
Provide default map as a loadable resource

### ISSUE THREAD

**Issue by oparisy** [KenneyNL/Starter-Kit-City-Builder#5]
Hi Kenney,

since I want to study your rendering choices in more details, I took the liberty to rebuild your screenshot's example map as a reference.

Maybe you want to bundle it as part of the github project? Either for peaple to copy in their `user://` folder, or maybe with some extra "load example map" bound key? (Maybe overkill, but that would provide an example of loading the resource from a project folder)

Please find attached my version of your map (I guess you kept a copy but hey): [map.zip](https://github.com/KenneyNL/Starter-Kit-City-Builder/files/12751754/map.zip)

**Comment by KenneyNL** [comment]
Hey, thanks - that's actually a wonderful idea. I've had my own sample map saved, and it's now included!
